# This is a basic workflow to help you get started with Actions

name: s3test1
on:
  push:
    branches: [ main ]
jobs:
  cypressTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cypress.io
        uses: cypress-io/github-action@v2.9.7
        with: 
          start: npm start

      
